# Generated by Django 2.2.7 on 2020-09-05 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managetemplate', '0005_auto_20200611_1719'),
    ]

    operations = [
        migrations.CreateModel(
            name='VariableCondition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variable_name', models.CharField(max_length=100)),
                ('condition_content', models.CharField(max_length=100)),
                ('use_excel_for_fulfill', models.BooleanField()),
                ('text_for_fulfill', models.CharField(max_length=1000)),
                ('use_excel_for_not_fulfill', models.BooleanField()),
                ('text_for_not_fulfill', models.CharField(max_length=1000)),
                ('project_name', models.CharField(max_length=100)),
            ],
        ),
    ]
