# Generated by Django 2.2.7 on 2020-10-13 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managetemplate', '0006_variablecondition'),
    ]

    operations = [
        migrations.CreateModel(
            name='PermutationGeneral',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=100)),
                ('update_status', models.BooleanField()),
                ('apply_to_all_para', models.BooleanField()),
                ('permutation_mode', models.CharField(max_length=100)),
                ('rand_from', models.IntegerField()),
                ('rand_to', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PermutationParagraphs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=100)),
                ('section_name', models.CharField(max_length=100)),
                ('section_visibility', models.BooleanField()),
                ('type', models.CharField(max_length=100)),
                ('number_of_elements', models.IntegerField()),
                ('permutation_mode', models.CharField(max_length=100)),
                ('rand_from', models.IntegerField()),
                ('rand_to', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PermutationProjects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
