# Generated by Django 2.2.7 on 2020-11-06 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managetemplate', '0008_permutationparagraphs_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='permutationgeneral',
            name='max_words',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='permutationgeneral',
            name='min_words',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='permutationparagraphs',
            name='max_words',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='permutationparagraphs',
            name='min_words',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
